# Generated by Django 2.0 on 2021-02-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('speed', models.CharField(max_length=10)),
                ('rpm', models.CharField(max_length=15)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Drivers')),
            ],
        ),
    ]
