# Generated by Django 2.0 on 2021-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='coolantTemp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='massAirFlow',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='throttlePosition',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='log_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='rpm',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='speed',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
